---
- name: add rpm key
  become: yes
  become_user: root
  rpm_key:
    state: present
    key: '{{rpm_key_url}}'

- name: add yum repo
  yum_repository:
    name: '{{rpm_repo_name}}' 
    description: '{{rpm_repo_description}}'
    baseurl: '{{rpm_base_url}}'
    enabled: yes
    gpgcheck: yes
    gpgkey: '{{rpm_key_url}}'
